### ISSUE TITLE
Segfault on syntax error

### ISSUE THREAD

**Issue by tturpin** [arnholm/angelcad-samples#1]
Hi,
I tried Angelcad, it looks interesting. However syntax error handling seems missing (could be helpful to learn the language):

To reproduce (on Ubuntu 18.04, installed with angelcad-1.3-02-ubuntu-18.04.3-lts.zip) :
- run angelcad
- open the screw_threads.as example
- build, view in angleview
- remove line 12 (the last point in the thread profile) -> syntax error due to the preceding ","
- redbuild
Everything appears to work, the STL file is even re-created, bug in fact as_csg segfaults.

**Comment by arnholm** [comment]
Hi and thanks for the report! If you remove line 12 in that file you must also remove the preceding comma, otherwise there is likely a null reference in the final array element. So did you get a segfault after removing the comma? I will check to see later if I can reproduce any segfault.

**Comment by arnholm** [comment]
Hi, I was able to reproduce this bug, thank you for reporting it! The bug is now fixed as shown
https://github.com/arnholm/angelcad/commit/2555bab06900046c1d2517411e38971b64de1ba2

After the fix, instead if segfaulting, the following error is now issued
asERR : (line 16, col 4) : polygon exception: NULL element detected in polygon points, index=4

The fix will be in the next release of AngelCAD.
